apiVersion: v1
data:
  url: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGItbW9uZ29kYi1yZXBsaWNhc2V0LTAubW9uZ29kYi1tb25nb2RiLXJlcGxpY2FzZXQsbW9uZ29kYi1tb25nb2RiLXJlcGxpY2FzZXQtMS5tb25nb2RiLW1vbmdvZGItcmVwbGljYXNldCxtb25nb2RiLW1vbmdvZGItcmVwbGljYXNldC0yLm1vbmdvZGItbW9uZ29kYi1yZXBsaWNhc2V0OjI3MDE3L2VjaG8/YXV0aFNvdXJjZT1hZG1pbg==
kind: Secret
metadata:
  creationTimestamp: "2020-08-12T13:20:49Z"
  name: echo-url-secret
  namespace: default
  resourceVersion: "435406"
  selfLink: /api/v1/namespaces/default/secrets/echo-url-secret
  uid: e1835855-ab4b-4b0f-ae84-cc171b39ca87
type: Opaque
